### ISSUE TITLE
Paused time has wrong values

### ISSUE THREAD

**Issue by wolfgang-ch** [wolfgang-ch/mytourbook#229] opened 2020-09-18 12:48 UTC
> 
> 
> I've several tours with wrong paused time, these are mainly tours which I recorded when driving by car but I also found 1 normal bicycle tour with wrong paused time value. These tours are all recorded with an Edge 1030 -> FIT format.
> 
> ![mt-stat-values](https://user-images.githubusercontent.com/1283445/93472071-7cef7d00-f8f4-11ea-97d9-eda9da3d6bd1.png)

I can't reproduce the issue so I'm not sure I can troubleshoot....unless you can share one or more FIT files ?

_Originally posted by @FJBDev in https://github.com/wolfgang-ch/mytourbook/pull/227#issuecomment-694406240_

**Comment by wolfgang-ch** [comment] 2020-09-18 12:51
I will investigate this, I've found more extreme examples. Your fix for negative paused times are not included in this test.

![mt-elapsed-vs-paused](https://user-images.githubusercontent.com/1283445/93598795-82fd6080-f9bd-11ea-9658-fd89be8965f9.png)

![mt-elapsed-vs-paused-2](https://user-images.githubusercontent.com/1283445/93598797-8395f700-f9bd-11ea-8078-a5bfced0e69a.png)

**Comment by wolfgang-ch** [comment] 2020-09-18 14:59
When dumping the paused start/end time, then there are some items where the start time is before the previous end time

![mt-next-start-before-end](https://user-images.githubusercontent.com/1283445/93611588-c7ddc300-f9ce-11ea-88e7-b0138940bf1c.png)

**Comment by wolfgang-ch** [comment] 2020-09-18 15:07
Tour Book view shows the computed diff: elapsed-recorded=paused

The statistic view shows the saved paused time which is computed with

https://github.com/wolfgang-ch/mytourbook/blob/64d8b860559b80e7f4cac8c761865b592bfa2d15/bundles/net.tourbook/src/net/tourbook/data/TourData.java#L8326-L8339

@FJBDev We have a big problem with the paused time :-)

How could it be solved when a paused start time is before the previous end time?
What value is correct?

**Comment by FJBDev** [comment] 2020-09-18 15:55
> 
> 
> I will investigate this, I've found more extreme examples. Your fix for negative paused times are not included in this test.
> 
> ![mt-elapsed-vs-paused](https://user-images.githubusercontent.com/1283445/93598795-82fd6080-f9bd-11ea-9658-fd89be8965f9.png)
> 
> ![mt-elapsed-vs-paused-2](https://user-images.githubusercontent.com/1283445/93598797-8395f700-f9bd-11ea-8078-a5bfced0e69a.png)

Ok, let me know when you test with my fix. I can't reproduce the issue as the FIT files I have don't have this issue.

**Comment by FJBDev** [comment] 2020-09-18 15:56
> 
> @FJBDev We have a big problem with the paused time :-)
> 
> How could it be solved when a paused start time is before the previous end time?
> What value is correct?

It's a good question, I've never seen this situation before. I can't reproduce the issue.

**Comment by FJBDev** [comment] 2020-09-18 16:01
> 
> 
> Tour Book view shows the computed diff: elapsed-recorded=paused
> 
> The statistic view shows the saved paused time which is computed with
> 
> https://github.com/wolfgang-ch/mytourbook/blob/64d8b860559b80e7f4cac8c761865b592bfa2d15/bundles/net.tourbook/src/net/tourbook/data/TourData.java#L8326-L8339
> 

I have fixed so that the TourBook used the value from the property `tourDeviceTime_Paused `in `TourData.java`

**Comment by wolfgang-ch** [comment] 2020-09-19 08:10
### Paused time issues

* Some tours have larger paused time than elapsed time (red rectangles)
* In the tour chart and 2D map, the paused time markers are at the wrong location

@FJBDev 
I'll send you some of these tours that you can test it.

![mt-paused-time-issues](https://user-images.githubusercontent.com/1283445/93662247-1175ee80-fa5f-11ea-8381-74fcbb0f2890.png)

**Comment by FJBDev** [comment] 2020-09-21 23:31
@wolfgang-ch 
Please see my latest [PR](https://github.com/wolfgang-ch/mytourbook/pull/233) that should address those issues.

**Comment by FJBDev** [comment] 2020-09-28 23:37
@wolfgang-ch per your recent testing, I think you can close this issue right ?

**Closed** 2020-09-29 04:42 UTC
